//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_EN() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPCalculator.Resources.en-EN", typeof(en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose language.
        /// </summary>
        internal static string CHOOSE_LANGUAGE {
            get {
                return ResourceManager.GetString("CHOOSE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty string.
        /// </summary>
        internal static string EMPTY_STRING {
            get {
                return ResourceManager.GetString("EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter number.
        /// </summary>
        internal static string ENTER_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter second number.
        /// </summary>
        internal static string ENTER_NUMBER2 {
            get {
                return ResourceManager.GetString("ENTER_NUMBER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter operation.
        /// </summary>
        internal static string ENTER_OPERATION {
            get {
                return ResourceManager.GetString("ENTER_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid char.
        /// </summary>
        internal static string INVALID_CHAR {
            get {
                return ResourceManager.GetString("INVALID_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose only languages in list.
        /// </summary>
        internal static string LIST_EXCEPTION {
            get {
                return ResourceManager.GetString("LIST_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minus coul be only one and at start.
        /// </summary>
        internal static string MINUS_EXCEPTION {
            get {
                return ResourceManager.GetString("MINUS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object.
        /// </summary>
        internal static string OBJECT_EXCEPTION {
            get {
                return ResourceManager.GetString("OBJECT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose one operation.
        /// </summary>
        internal static string OPERATION_EXCAPTION {
            get {
                return ResourceManager.GetString("OPERATION_EXCAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result.
        /// </summary>
        internal static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only roman numbers.
        /// </summary>
        internal static string ROMAN_NUMBERS {
            get {
                return ResourceManager.GetString("ROMAN_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System exception. Program is terminated.
        /// </summary>
        internal static string SYSTEM_EXCETION {
            get {
                return ResourceManager.GetString("SYSTEM_EXCETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type unsupported.
        /// </summary>
        internal static string UNSUPPORTED_TYPE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_TYPE", resourceCulture);
            }
        }
    }
}
