//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPCalculator.Resources.ru-RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        internal static string CHOOSE_LANGUAGE {
            get {
                return ResourceManager.GetString("CHOOSE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустая срока.
        /// </summary>
        internal static string EMPTY_STRING {
            get {
                return ResourceManager.GetString("EMPTY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите число.
        /// </summary>
        internal static string ENTER_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите второе число.
        /// </summary>
        internal static string ENTER_NUMBER2 {
            get {
                return ResourceManager.GetString("ENTER_NUMBER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите операцию.
        /// </summary>
        internal static string ENTER_OPERATION {
            get {
                return ResourceManager.GetString("ENTER_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный символ.
        /// </summary>
        internal static string INVALID_CHAR {
            get {
                return ResourceManager.GetString("INVALID_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите только те языки которые есть в списке.
        /// </summary>
        internal static string LIST_EXCEPTION {
            get {
                return ResourceManager.GetString("LIST_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минус может быть только один и в начале.
        /// </summary>
        internal static string MINUS_EXCEPTION {
            get {
                return ResourceManager.GetString("MINUS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект.
        /// </summary>
        internal static string OBJECT_EXCEPTION {
            get {
                return ResourceManager.GetString("OBJECT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите из доступгых операций.
        /// </summary>
        internal static string OPERATION_EXCAPTION {
            get {
                return ResourceManager.GetString("OPERATION_EXCAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только римские цифры.
        /// </summary>
        internal static string ROMAN_NUMBERS {
            get {
                return ResourceManager.GetString("ROMAN_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип неопределён.
        /// </summary>
        internal static string UNSUPPORTED_TYPE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_TYPE", resourceCulture);
            }
        }
    }
}
